### ISSUE TITLE
JSON/YAML/etc. configuration files?

### ISSUE THREAD

**Issue by musjj** [directvt/vtm#326]
What do you think of adding a JSON/YAML/etc. configuration format?
I think it would make it way easier to introduce to new users.

**Comment by o-sdn-o** [comment]
Hi! I support this idea. We will need to implement the format converter used by vtm to JSON/YAML/etc and vice versa. Perhaps in the future one of these formats will be more convenient than the one used in vtm now. The use of vtm in its own format is due to the need to inline attribute records (for brevity) while not losing the algorithmic simplicity of merging two such configurations

```xml
<background>
  <fgc>whitedk</fgc>
  <bgc>blacklt</bgc>
  <tile>"#   \n    "</tile>
</background>
```
the same but shorter
```xml
<background fgc=whitedk bgc=blacklt tile="#   \n    "/>
```

To convert to other serialization formats, we can translate the vtm format into some canonical form that is compatible with other formats. To do this, we need to introduce a new parameter for each attribute - `_value_` - which contains the attribute's own value.

Canonical form
```xml
<background>
  <_value_><_value_>
  <fgc>
    <_value_>whitedk<_value_>
  </fgc>
  <bgc>
    <_value_>blacklt<_value_>
  </bgc>
  <tile>
    <_value_>"#   \n    "<_value_>
  </tile>
</background>
```

JSON
```json
{
    "background": {
        "_value_": "",
        "fgc": {
            "_value_": "whitedk",
        },
        "bgc": {
            "_value_": "blacklt",
        },
        "tile": {
            "_value_": "#   \n    ",
        },
    },
}
```

YAML
```yaml
    background:
        - _value_: ""
        - fgc
            - _value_: whitedk
        - bgc
            - _value_: blacklt
        - tile
            - _value_: "#   \n    "
```
